version: '3'
services:
  server:
    build: ./server/
    expose:
      - "8081"
    restart: always

    # Add any additional configuration for the server service

  client:
    build: ./client/
    expose:
      - "3000"
    restart: always
    # Add any additional configuration for the client service

  front:
    image: nginx
    depends_on:
      - server
      - client
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    restart: always






